### ISSUE TITLE
register username/mail handling error message is problematic

### ISSUE THREAD

**Issue by bakayim** [oztiryakimeric/Quizzy#12]
suppose that i have an account with credentials, username:batuhan mail:batuhan.kayim@ozu.edu.tr

when i try to register new user with "username batuhan" it gives me the error batuhan is already taken. OK.

when i try to register new user with "username batuhan2" and "email batuhan.kayim@ozu.edu.tr" it gives me the error "batuhan2 is already taken"

error message should be generalised as "this username or password is already in use"

**Comment by damlakarakulah** [comment]
solved
